before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd
    ldflags:
      - -s -w
      - -X github.com/qba73/manhat.version={{.Tag}}
      - -X github.com/qba73/manhat.vcsref={{.Commit}}
      - -X github.com/qba73/manhat.buildtime={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: qba73
    name: manhat
  draft: false
  prerelease: false
  name_template: "v{{.Version}}"
  disable: false
